### PR TITLE
Websocket connection in template

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Required by https://github.com/fslaborg/FsLab.Templates/pull/2

### CODE REVIEW

**Comment by tpetricek** [comment]
Can we wrap this in some sort of `try .. catch` to avoid too ugly error messages in case web sockets are not supported?

**Comment by Krzysztof-Cieslak** [comment]
Done

**Comment by tpetricek** [comment]
I suppose the error would actually happen inside the `init` function, so the exception handler should be there?

**Comment by Krzysztof-Cieslak** [comment]
Argh... sorry, that was pretty stupid. Fixed

**Pull request merged**
