### PR TITLE
Increase png size for better web reports

### PR DESCRIPTION
**Pull request by damageboy**
Make PNGs larger, .css for resizing them is already in place because of bootstrap's css

### CODE REVIEW

**Comment by tpetricek** [comment]
Thanks! 

Have you tested what does this do to the PDF output? (To test that, you need to install `pdflatex` and then run `build pdf` from the command line in the folder where the FsLab Journal has been created.)

**Comment by damageboy** [comment]
Have not.
I will and report...

**Comment by tpetricek** [comment]
Ping! Did you have any chance to try how this looks in LaTeX? 
If that work, I think it would be nice to merge the PR!

**Comment by damageboy** [comment]
No, I haven't done it yet.
Let me try and see how painful it is to get TeX running

**Comment by tpetricek** [comment]
The latest beta does this a bit differently, so I think we'd need to revisit how this is done in the new version.

**Pull request closed without merging**
